name: BuildPage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Node 18 Server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: joshthedevelopa/artist-portfolio

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm install

      - run: npm run build

      - name: Run my action
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: js/dist/
