name: BuildPage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    name: Node 18 Server
    steps:
      - uses: actions/checkout@v3
        with:
          repository: joshthedevelopa/artist-portfolio

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm install

      - run: npm run build

      - name: Run my action
        uses: ./